### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by taylorshuang** [UlordChain/Ulord-platform#2]
I can't open UCwallet and UCWallet-server's link in readme, https://github.com/UlordChain/Ulord-platform/blob/master/UCwallet and  https://github.com/UlordChain/Ulord-platform/blob/master/UCWallet-server

**Comment by yinhaibo** [comment]
Curently there is no UCWallet source code. Testing UCWallet code in wallet directory，please access to https://github.com/UlordChain/Ulord-platform/tree/master/Uwallet
